---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  postgres_user: {{ .Values.env.postgresUser | quote }}
  postgres_password: {{ .Values.env.postgresPassword | quote }}
{{- if .Values.global.vault.enabled }}
  vault_token: {{ .Values.global.vault.vaultToken | quote }}
{{- end }}
